#!/bin/bash -xve

# Gather data
./fedmsg2gource.py --category git --start 1420088400 --end 1451624400 > logs/2015-git.log
./fedmsg2gource.py --category wiki --start 1420088400 --end 1451624400 > logs/2015-wiki.log
./fedmsg2gource.py --category copr --start 1420088400 --end 1451624400 > logs/2015-copr.log
./fedmsg2gource.py --category anitya --start 1420088400 --end 1451624400 > logs/2015-anitya.log
# ./fedmsg2gource.py --category mirrormanager --start 1420088400 --end 1451624400 > logs/2015-mirrormanager.log
./fedmsg2gource.py --category pungi --start 1420088400 --end 1451624400 > logs/2015-pungi.log
./fedmsg2gource.py --category ansible --start 1420088400 --end 1451624400 > logs/2015-ansible.log
./fedmsg2gource.py --category fedoratagger --start 1420088400 --end 1451624400 > logs/2015-fedoratagger.log
./fedmsg2gource.py --category pkgdb --start 1420088400 --end 1451624400 > logs/2015-pkgdb.log
# ./fedmsg2gource.py --category summershum --start 1420088400 --end 1451624400 > logs/2015-summershum.log
./fedmsg2gource.py --category nuancier --start 1420088400 --end 1451624400 > logs/2015-nuancier.log
./fedmsg2gource.py --category releng --start 1420088400 --end 1451624400 > logs/2015-releng.log
./fedmsg2gource.py --category mailman --start 1420088400 --end 1451624400 > logs/2015-mailman.log
./fedmsg2gource.py --category autocloud --start 1420088400 --end 1451624400 > logs/2015-autocloud.log
./fedmsg2gource.py --category fedbadges --start 1420088400 --end 1451624400 > logs/2015-fedbadges.log
./fedmsg2gource.py --category fmn --start 1420088400 --end 1451624400 > logs/2015-fmn.log
./fedmsg2gource.py --category koschei --start 1420088400 --end 1451624400 > logs/2015-koschei.log
./fedmsg2gource.py --category compose --start 1420088400 --end 1451624400 > logs/2015-compose.log
./fedmsg2gource.py --category fedimg --start 1420088400 --end 1451624400 > logs/2015-fedimg.log
./fedmsg2gource.py --category jenkins --start 1420088400 --end 1451624400 > logs/2015-jenkins.log
./fedmsg2gource.py --category irc --start 1420088400 --end 1451624400 > logs/2015-irc.log
# ./fedmsg2gource.py --category datanommer --start 1420088400 --end 1451624400 > logs/2015-datanommer.log
# ./fedmsg2gource.py --category zanata --start 1420088400 --end 1451624400 > logs/2015-zanata.log
./fedmsg2gource.py --category fas --start 1420088400 --end 1451624400 > logs/2015-fas.log
./fedmsg2gource.py --category buildsys --start 1420088400 --end 1451624400 > logs/2015-buildsys.log
./fedmsg2gource.py --category askbot --start 1420088400 --end 1451624400 > logs/2015-askbot.log
./fedmsg2gource.py --category pagure --start 1420088400 --end 1451624400 > logs/2015-pagure.log
./fedmsg2gource.py --category bodhi --start 1420088400 --end 1451624400 > logs/2015-bodhi.log
./fedmsg2gource.py --category mdapi --start 1420088400 --end 1451624400 > logs/2015-mdapi.log
./fedmsg2gource.py --category taskotron --start 1420088400 --end 1451624400 > logs/2015-taskotron.log
./fedmsg2gource.py --category nagios --start 1420088400 --end 1451624400 > logs/2015-nagios.log
# ./fedmsg2gource.py --category faf --start 1420088400 --end 1451624400 > logs/2015-faf.log
./fedmsg2gource.py --category kerneltest --start 1420088400 --end 1451624400 > logs/2015-kerneltest.log
./fedmsg2gource.py --category github --start 1420088400 --end 1451624400 > logs/2015-github.log
./fedmsg2gource.py --category trac --start 1420088400 --end 1451624400 > logs/2015-trac.log
./fedmsg2gource.py --category meetbot --start 1420088400 --end 1451624400 > logs/2015-meetbot.log
./fedmsg2gource.py --category fedora_elections --start 1420088400 --end 1451624400 > logs/2015-fedora_elections.log
./fedmsg2gource.py --category planet --start 1420088400 --end 1451624400 > logs/2015-planet.log
./fedmsg2gource.py --category bugzilla --start 1420088400 --end 1451624400 > logs/2015-bugzilla.log
./fedmsg2gource.py --category fedocal --start 1420088400 --end 1451624400 > logs/2015-fedocal.log
./fedmsg2gource.py --category infragit --start 1420088400 --end 1451624400 > logs/2015-infragit.log
./fedmsg2gource.py --category hotness --start 1420088400 --end 1451624400 > logs/2015-hotness.log
# ./fedmsg2gource.py --category announce --start 1420088400 --end 1451624400 > logs/2015-announce.log
# ./fedmsg2gource.py --category logger --start 1420088400 --end 1451624400 > logs/2015-logger.log


# Visualize it
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora version control system (Package Commits)'  --path ./logs/2015-git.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-git-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Wiki (Wiki Edits)'  --path ./logs/2015-wiki.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-wiki-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora the Cool Other Package Repositories system (Extra Repository Updates)'  --path ./logs/2015-copr.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-copr-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Upstream Release Monitoring (Upstream Releases)'  --path ./logs/2015-anitya.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-anitya-plain.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Mirror Manager activity (Mirror Updates)'  --path ./logs/2015-mirrormanager.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-mirrormanager-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Release Engineering (Composes)'  --path ./logs/2015-pungi.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-pungi-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Infrastructure Ansible Runs (Ansible Runs)'  --path ./logs/2015-ansible.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-ansible-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora package labeller/tagger (Package Tag Votes)'  --path ./logs/2015-fedoratagger.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedoratagger-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Package DB (Package ACL Updates)'  --path ./logs/2015-pkgdb.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-pkgdb-plain.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora a backend tool that extracts hashes of source files (Source File Hashes)'  --path ./logs/2015-summershum.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-summershum-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora the supplemental wallpaper voting system (Wallpaper Elections)'  --path ./logs/2015-nuancier.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-nuancier-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Release Engineering (Releng Events)'  --path ./logs/2015-releng.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-releng-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora mailing list messages (Mailing List Messages)'  --path ./logs/2015-mailman.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-mailman-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Automated Fedora Cloud Image Testing service (Cloud Image Test)'  --path ./logs/2015-autocloud.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-autocloud-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Open Badges System (New Badges)'  --path ./logs/2015-fedbadges.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedbadges-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Notifications System (Notification Preference Updates)'  --path ./logs/2015-fmn.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fmn-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Continuous integration for Fedora packages (Watched packages)'  --path ./logs/2015-koschei.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-koschei-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Release Engineering (Composes)'  --path ./logs/2015-compose.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-compose-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'The Fedora cloud image service (New cloud image upload)'  --path ./logs/2015-fedimg.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedimg-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Jenkins CI system (Jenkins build status)'  --path ./logs/2015-jenkins.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-jenkins-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora IRC Karma (IRC Karma)'  --path ./logs/2015-irc.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-irc-plain.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Exceptional Datanommer Events (Datanommer Events)'  --path ./logs/2015-datanommer.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-datanommer-plain.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora translation events (Translation Events)'  --path ./logs/2015-zanata.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-zanata-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Account System (Account Changes)'  --path ./logs/2015-fas.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fas-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora build system (Koji Builds)'  --path ./logs/2015-buildsys.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-buildsys-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora 'Ask' Forum (Ask Fedora Qs & As)'  --path ./logs/2015-askbot.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-askbot-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Pagure forge (Pagure forge)'  --path ./logs/2015-pagure.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-pagure-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora update system (Package Updates)'  --path ./logs/2015-bodhi.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-bodhi-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora repository meta-data API (Medata API update)'  --path ./logs/2015-mdapi.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-mdapi-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Framework for automated task execution (Automated task results)'  --path ./logs/2015-taskotron.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-taskotron-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Infra Service Monitoring (Service Outage Alerts)'  --path ./logs/2015-nagios.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-nagios-plain.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora ABRT crash analysis server (New and significant crashes)'  --path ./logs/2015-faf.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-faf-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Kernel Testing Initiative (Kernel Tests)'  --path ./logs/2015-kerneltest.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-kerneltest-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora-related Github Repos (Github Events)'  --path ./logs/2015-github.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-github-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'events from select Fedora Hosted projects (Fedora Hosted Events)'  --path ./logs/2015-trac.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-trac-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora IRC bot (IRC Meetings)'  --path ./logs/2015-meetbot.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-meetbot-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the fedora voting system (Fedora Elections)'  --path ./logs/2015-fedora_elections.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedora_elections-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora blog aggregator (Blog Posts)'  --path ./logs/2015-planet.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-planet-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Red Hat Bugzilla (Bug Updates)'  --path ./logs/2015-bugzilla.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-bugzilla-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'The Fedora Calendaring System (Calendar Events)'  --path ./logs/2015-fedocal.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedocal-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Infrastructure repos (Infrastructure Commits)'  --path ./logs/2015-infragit.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-infragit-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora A fedmsg consumer that files bugzilla bugs for upstream releases (Fresh Builds & Bugs)'  --path ./logs/2015-hotness.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-hotness-plain.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Official Fedora Announcements (Announcements)'  --path ./logs/2015-announce.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-announce-plain.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'miscellaneous Fedora Infrastructure shell scripts (System Logs)'  --path ./logs/2015-logger.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-logger-plain.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora version control system (Package Commits)' --hide dirnames --path ./logs/2015-git.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-git-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Wiki (Wiki Edits)' --hide dirnames --path ./logs/2015-wiki.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-wiki-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora the Cool Other Package Repositories system (Extra Repository Updates)' --hide dirnames --path ./logs/2015-copr.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-copr-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Upstream Release Monitoring (Upstream Releases)' --hide dirnames --path ./logs/2015-anitya.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-anitya-without-dirnames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Mirror Manager activity (Mirror Updates)' --hide dirnames --path ./logs/2015-mirrormanager.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-mirrormanager-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Release Engineering (Composes)' --hide dirnames --path ./logs/2015-pungi.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-pungi-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Infrastructure Ansible Runs (Ansible Runs)' --hide dirnames --path ./logs/2015-ansible.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-ansible-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora package labeller/tagger (Package Tag Votes)' --hide dirnames --path ./logs/2015-fedoratagger.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedoratagger-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Package DB (Package ACL Updates)' --hide dirnames --path ./logs/2015-pkgdb.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-pkgdb-without-dirnames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora a backend tool that extracts hashes of source files (Source File Hashes)' --hide dirnames --path ./logs/2015-summershum.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-summershum-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora the supplemental wallpaper voting system (Wallpaper Elections)' --hide dirnames --path ./logs/2015-nuancier.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-nuancier-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Release Engineering (Releng Events)' --hide dirnames --path ./logs/2015-releng.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-releng-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora mailing list messages (Mailing List Messages)' --hide dirnames --path ./logs/2015-mailman.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-mailman-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Automated Fedora Cloud Image Testing service (Cloud Image Test)' --hide dirnames --path ./logs/2015-autocloud.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-autocloud-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Open Badges System (New Badges)' --hide dirnames --path ./logs/2015-fedbadges.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedbadges-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Notifications System (Notification Preference Updates)' --hide dirnames --path ./logs/2015-fmn.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fmn-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Continuous integration for Fedora packages (Watched packages)' --hide dirnames --path ./logs/2015-koschei.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-koschei-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Release Engineering (Composes)' --hide dirnames --path ./logs/2015-compose.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-compose-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'The Fedora cloud image service (New cloud image upload)' --hide dirnames --path ./logs/2015-fedimg.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedimg-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Jenkins CI system (Jenkins build status)' --hide dirnames --path ./logs/2015-jenkins.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-jenkins-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora IRC Karma (IRC Karma)' --hide dirnames --path ./logs/2015-irc.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-irc-without-dirnames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Exceptional Datanommer Events (Datanommer Events)' --hide dirnames --path ./logs/2015-datanommer.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-datanommer-without-dirnames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora translation events (Translation Events)' --hide dirnames --path ./logs/2015-zanata.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-zanata-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Account System (Account Changes)' --hide dirnames --path ./logs/2015-fas.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fas-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora build system (Koji Builds)' --hide dirnames --path ./logs/2015-buildsys.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-buildsys-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora 'Ask' Forum (Ask Fedora Qs & As)' --hide dirnames --path ./logs/2015-askbot.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-askbot-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Pagure forge (Pagure forge)' --hide dirnames --path ./logs/2015-pagure.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-pagure-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora update system (Package Updates)' --hide dirnames --path ./logs/2015-bodhi.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-bodhi-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora repository meta-data API (Medata API update)' --hide dirnames --path ./logs/2015-mdapi.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-mdapi-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Framework for automated task execution (Automated task results)' --hide dirnames --path ./logs/2015-taskotron.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-taskotron-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Infra Service Monitoring (Service Outage Alerts)' --hide dirnames --path ./logs/2015-nagios.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-nagios-without-dirnames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora ABRT crash analysis server (New and significant crashes)' --hide dirnames --path ./logs/2015-faf.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-faf-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Kernel Testing Initiative (Kernel Tests)' --hide dirnames --path ./logs/2015-kerneltest.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-kerneltest-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora-related Github Repos (Github Events)' --hide dirnames --path ./logs/2015-github.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-github-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'events from select Fedora Hosted projects (Fedora Hosted Events)' --hide dirnames --path ./logs/2015-trac.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-trac-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora IRC bot (IRC Meetings)' --hide dirnames --path ./logs/2015-meetbot.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-meetbot-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the fedora voting system (Fedora Elections)' --hide dirnames --path ./logs/2015-fedora_elections.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedora_elections-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora blog aggregator (Blog Posts)' --hide dirnames --path ./logs/2015-planet.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-planet-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Red Hat Bugzilla (Bug Updates)' --hide dirnames --path ./logs/2015-bugzilla.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-bugzilla-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'The Fedora Calendaring System (Calendar Events)' --hide dirnames --path ./logs/2015-fedocal.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedocal-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Infrastructure repos (Infrastructure Commits)' --hide dirnames --path ./logs/2015-infragit.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-infragit-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora A fedmsg consumer that files bugzilla bugs for upstream releases (Fresh Builds & Bugs)' --hide dirnames --path ./logs/2015-hotness.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-hotness-without-dirnames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Official Fedora Announcements (Announcements)' --hide dirnames --path ./logs/2015-announce.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-announce-without-dirnames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'miscellaneous Fedora Infrastructure shell scripts (System Logs)' --hide dirnames --path ./logs/2015-logger.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-logger-without-dirnames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora version control system (Package Commits)' --hide dirnames,filenames --path ./logs/2015-git.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-git-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Wiki (Wiki Edits)' --hide dirnames,filenames --path ./logs/2015-wiki.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-wiki-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora the Cool Other Package Repositories system (Extra Repository Updates)' --hide dirnames,filenames --path ./logs/2015-copr.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-copr-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Upstream Release Monitoring (Upstream Releases)' --hide dirnames,filenames --path ./logs/2015-anitya.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-anitya-without-filenames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Mirror Manager activity (Mirror Updates)' --hide dirnames,filenames --path ./logs/2015-mirrormanager.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-mirrormanager-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Release Engineering (Composes)' --hide dirnames,filenames --path ./logs/2015-pungi.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-pungi-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Infrastructure Ansible Runs (Ansible Runs)' --hide dirnames,filenames --path ./logs/2015-ansible.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-ansible-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora package labeller/tagger (Package Tag Votes)' --hide dirnames,filenames --path ./logs/2015-fedoratagger.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedoratagger-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Package DB (Package ACL Updates)' --hide dirnames,filenames --path ./logs/2015-pkgdb.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-pkgdb-without-filenames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora a backend tool that extracts hashes of source files (Source File Hashes)' --hide dirnames,filenames --path ./logs/2015-summershum.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-summershum-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora the supplemental wallpaper voting system (Wallpaper Elections)' --hide dirnames,filenames --path ./logs/2015-nuancier.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-nuancier-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Release Engineering (Releng Events)' --hide dirnames,filenames --path ./logs/2015-releng.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-releng-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora mailing list messages (Mailing List Messages)' --hide dirnames,filenames --path ./logs/2015-mailman.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-mailman-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Automated Fedora Cloud Image Testing service (Cloud Image Test)' --hide dirnames,filenames --path ./logs/2015-autocloud.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-autocloud-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Open Badges System (New Badges)' --hide dirnames,filenames --path ./logs/2015-fedbadges.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedbadges-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Notifications System (Notification Preference Updates)' --hide dirnames,filenames --path ./logs/2015-fmn.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fmn-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Continuous integration for Fedora packages (Watched packages)' --hide dirnames,filenames --path ./logs/2015-koschei.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-koschei-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Release Engineering (Composes)' --hide dirnames,filenames --path ./logs/2015-compose.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-compose-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'The Fedora cloud image service (New cloud image upload)' --hide dirnames,filenames --path ./logs/2015-fedimg.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedimg-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Jenkins CI system (Jenkins build status)' --hide dirnames,filenames --path ./logs/2015-jenkins.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-jenkins-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora IRC Karma (IRC Karma)' --hide dirnames,filenames --path ./logs/2015-irc.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-irc-without-filenames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Exceptional Datanommer Events (Datanommer Events)' --hide dirnames,filenames --path ./logs/2015-datanommer.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-datanommer-without-filenames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora translation events (Translation Events)' --hide dirnames,filenames --path ./logs/2015-zanata.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-zanata-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora Account System (Account Changes)' --hide dirnames,filenames --path ./logs/2015-fas.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fas-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora build system (Koji Builds)' --hide dirnames,filenames --path ./logs/2015-buildsys.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-buildsys-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora 'Ask' Forum (Ask Fedora Qs & As)' --hide dirnames,filenames --path ./logs/2015-askbot.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-askbot-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Pagure forge (Pagure forge)' --hide dirnames,filenames --path ./logs/2015-pagure.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-pagure-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora update system (Package Updates)' --hide dirnames,filenames --path ./logs/2015-bodhi.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-bodhi-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora repository meta-data API (Medata API update)' --hide dirnames,filenames --path ./logs/2015-mdapi.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-mdapi-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Framework for automated task execution (Automated task results)' --hide dirnames,filenames --path ./logs/2015-taskotron.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-taskotron-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Infra Service Monitoring (Service Outage Alerts)' --hide dirnames,filenames --path ./logs/2015-nagios.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-nagios-without-filenames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora ABRT crash analysis server (New and significant crashes)' --hide dirnames,filenames --path ./logs/2015-faf.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-faf-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Kernel Testing Initiative (Kernel Tests)' --hide dirnames,filenames --path ./logs/2015-kerneltest.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-kerneltest-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora-related Github Repos (Github Events)' --hide dirnames,filenames --path ./logs/2015-github.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-github-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'events from select Fedora Hosted projects (Fedora Hosted Events)' --hide dirnames,filenames --path ./logs/2015-trac.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-trac-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora IRC bot (IRC Meetings)' --hide dirnames,filenames --path ./logs/2015-meetbot.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-meetbot-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the fedora voting system (Fedora Elections)' --hide dirnames,filenames --path ./logs/2015-fedora_elections.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedora_elections-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'the Fedora blog aggregator (Blog Posts)' --hide dirnames,filenames --path ./logs/2015-planet.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-planet-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Red Hat Bugzilla (Bug Updates)' --hide dirnames,filenames --path ./logs/2015-bugzilla.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-bugzilla-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'The Fedora Calendaring System (Calendar Events)' --hide dirnames,filenames --path ./logs/2015-fedocal.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-fedocal-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora Infrastructure repos (Infrastructure Commits)' --hide dirnames,filenames --path ./logs/2015-infragit.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-infragit-without-filenames.webm
gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Fedora A fedmsg consumer that files bugzilla bugs for upstream releases (Fresh Builds & Bugs)' --hide dirnames,filenames --path ./logs/2015-hotness.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-hotness-without-filenames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'Official Fedora Announcements (Announcements)' --hide dirnames,filenames --path ./logs/2015-announce.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-announce-without-filenames.webm
# gource -i 6 --user-image-dir ~/.cache/avatars --log-format custom --stop-at-end --title 'miscellaneous Fedora Infrastructure shell scripts (System Logs)' --hide dirnames,filenames --path ./logs/2015-logger.log -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K webm/2015-logger-without-filenames.webm
